- name: Enable CRB repo for RHEL9 variation.
  command: dnf config-manager --set-enabled crb
  when:
    - ansible_distribution_major_version == "9"
    - (ansible_distribution == "AlmaLinux") or (ansible_distribution == "Rocky") or (ansible_distribution == "CentOS")
- name: checking yum repo
  stat:
    path: /etc/yum.repos.d/pgdg-redhat-all.repo
  register: stat_yum_repo
- name: Import PGDG GPG key
  ansible.builtin.rpm_key:
    state: present
    key: "https://ftp.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL"
- name: Install PostgreSQL repository
  yum: 
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
  when: not stat_yum_repo.stat.exists
- name: Install python3-passlib for htpasswd
  package:
    name: python3-passlib
    state: present
- name: Install psycopg2 for PostgreSQL control
  package:
    name: python3-psycopg2
    state: present
- name: "Install PostgreSQL {{ psql_version }} Server"
  package: 
    name: "postgresql{{ psql_version }}-server"
    state: present
- name: "Checking the DB is ready."
  stat:
    path: "/var/lib/pgsql/{{ psql_version }}/data/pg_hba.conf"
  register: psql_data
- name: "Initilizing PostgreSQL DB"
  command: /usr/pgsql-{{ psql_version }}/bin/postgresql-{{ psql_version }}-setup initdb
  when: not psql_data.stat.exists  
  notify: configure DB
- name: "pg_hba.conf 설정을 통해 DB 접근권한 수정"
  copy: 
    dest: "/var/lib/pgsql/{{ psql_version }}/data/pg_hba.conf"
    owner: postgres
    group: postgres
    content: "local   all             all                                     trust\n
host    all             all             127.0.0.1/32            trust\n
host    all             all             ::1/128                 trust\n
local   replication   all   peer
host    replication   replication   192.168.124.0/24    scram-sha-256
"  
